/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assist.view;

import assist.controller.routineDAO;
import assist.model.routine;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class droutine extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    /**
     * Creates new form droutine
     */
    public droutine() {
        initComponents();
        model = new DefaultTableModel(null,new Object[]{"Id","Start Time","Activity","End Time"});
        jTable_routine.setModel(model);
        
        Date today = new Date();
        jLabel_date.setText(today.toString());
    }

    private void clearfields(){
        jTextField_reference.setText("0");
        jTextField_reference.setEditable(false);
        jTextField_starttime.setText("00:00");
        jTextField_endtime.setText("00:00");
        jTextArea_activity.setText("");
    }
    
    private void clearTable()
    {
        int count = jTable_routine.getRowCount();
        for(int i=0; i<count;i++)
        {
            model.removeRow(0);
        }
    }
    
    private void LoadData(){
        routineDAO rDAO = new routineDAO();
        ArrayList<routine> list = rDAO.fetchData();
        clearTable();
        for (int i = 0; i<list.size(); i++)
        {
                model.addRow(new Object[]{
                list.get(i).getId(),
                list.get(i).getStarttime(),
                list.get(i).getActivity(),
                list.get(i).getEndtime()                    
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_reference = new javax.swing.JTextField();
        jLabel_date = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_starttime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_activity = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField_endtime = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_show = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_routine = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Daily Routine");

        jTextField_reference.setText("0");

        jLabel_date.setText("Date");

        jLabel_id.setText("0");

        jLabel2.setText("Start Time");

        jTextField_starttime.setText("00:00");
        jTextField_starttime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_starttimeKeyTyped(evt);
            }
        });

        jTextArea_activity.setColumns(20);
        jTextArea_activity.setRows(5);
        jTextArea_activity.setText("Write the activity to do during\nthis time.");
        jScrollPane1.setViewportView(jTextArea_activity);

        jLabel3.setText("End Time");

        jTextField_endtime.setText("00:00");
        jTextField_endtime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_endtimeKeyTyped(evt);
            }
        });

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_show.setText("Show Routine");
        jButton_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear Routine");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jTable_routine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_routine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_routineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_routine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_starttime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_edit)
                                .addGap(87, 87, 87)
                                .addComponent(jButton_delete)
                                .addGap(43, 43, 43)
                                .addComponent(jButton_cancel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_endtime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_show)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_clear))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_date)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_endtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_add)
                                    .addComponent(jButton_cancel)
                                    .addComponent(jButton_edit)
                                    .addComponent(jButton_delete)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_reference)
                                    .addComponent(jLabel_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_starttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_show)
                    .addComponent(jButton_clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        String stime = jTextField_starttime.getText();
        String etime = jTextField_endtime.getText();
        String activity = jTextArea_activity.getText();
        String reference = jTextField_reference.getText();
        
        routine ob = new routine();
        ob.setStarttime(stime);
        ob.setEndtime(etime);
        ob.setActivity(activity);
        ob.setReference(reference);
        routineDAO rDAO = new routineDAO();//hand over this model class to controller class
        rDAO.insertData(ob);
        JOptionPane.showMessageDialog(null,"An Activity Added.");
        //clear all the fields
        clearfields();
        LoadData();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        int id =Integer.parseInt(jLabel_id.getText());
        routine ab = new routine();
        ab.setId(id);
        routineDAO ob = new routineDAO();
        int deleteoption = JOptionPane.showConfirmDialog(null,"Do you want to delete?");
        if(deleteoption == JOptionPane.YES_OPTION) {
        ob.deleteData(ab);
        JOptionPane.showMessageDialog(null,"An Activity Deleted");
        LoadData();
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        int id =Integer.parseInt(jLabel_id.getText());
        String stime = jTextField_starttime.getText();
        String etime = jTextField_endtime.getText();
        String activity = jTextArea_activity.getText();  
        routine ob = new routine();
        ob.setId(id);
        ob.setStarttime(stime);
        ob.setEndtime(etime);
        ob.setActivity(activity);
        routineDAO evntDAO = new routineDAO();//hand over this model class to controller class
        evntDAO.updateData(ob);
        //clear all the fields
        JOptionPane.showMessageDialog(null,"Selected Activity Edited");
        LoadData(); 
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        routineDAO ob = new routineDAO();
        ob.clearAll();
        JOptionPane.showMessageDialog(null,"Routine Deleted");
        LoadData();
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        clearfields();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jButton_showActionPerformed

    private void jTable_routineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_routineMouseClicked
        // TODO add your handling code here:
        int row = jTable_routine.getSelectedRow();
        jLabel_id.setText(jTable_routine.getValueAt(row,0).toString());
        jTextField_starttime.setText(jTable_routine.getValueAt(row,1).toString());
        jTextArea_activity.setText(jTable_routine.getValueAt(row,2).toString());
        jTextField_endtime.setText(jTable_routine.getValueAt(row,3).toString()); 
    }//GEN-LAST:event_jTable_routineMouseClicked

    private void jTextField_starttimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_starttimeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_starttimeKeyTyped

    private void jTextField_endtimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_endtimeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_endtimeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_routine;
    private javax.swing.JTextArea jTextArea_activity;
    private javax.swing.JTextField jTextField_endtime;
    private javax.swing.JTextField jTextField_reference;
    private javax.swing.JTextField jTextField_starttime;
    // End of variables declaration//GEN-END:variables
}
